spring.application.name=coresh

server.port=5600

spring.main.banner-mode=off

logging.pattern.console=Coresh | %5p | %d{yyyy-MM-dd HH:mm:ss} | %m%n

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

influx.db=${INFLUX_DB:metrics}
influx.username=${INFLUX_USERNAME:admin}
influx.password=${INFLUX_PASSWORD:adminpass}
influx.url=${INFLUX_URL:http://localhost:8086}

jaeger.url=${JAEGER_URL:http://localhost:16686}

schedule.checks.interval=${EXECUTIONS_SCHEDULE:60000}