spring.application.name=coresh

server.port=5600

spring.main.banner-mode=off

logging.pattern.console=Coresh | %5p | %d{yyyy-MM-dd HH:mm:ss} | %m%n

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

influx.db=${INFLUX_DB:metrics}
influx.username=${INFLUX_USERNAME:admin}
influx.password=${INFLUX_PASSWORD:adminpass}
influx.url=${INFLUX_URL:http://localhost:8086}

jaeger.url=${JAEGER_URL:http://localhost:16686}

schedule.checks.interval=${EXECUTIONS_SCHEDULE:60000}

keygen.account.id=904c91fb-38c5-40bd-9d77-355c42e6e6d6
keygen.api.token=Bearer prod-7196976091f2a14ae35e0e0010b30eed15647fea5670138c577184ccdf1a3f5fv3
keygen.product.id=dade50f0-70ba-41b0-b59f-e96e45223b6d
keygen.secret.hmac.key=pX42WeLz*2qY@wV1%4(7&mN5^cC8(h43#